### PR TITLE
use 'thiserror' to define 'Error'

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by davegarred** [comment]
I don't know that this adds enough value to warrant pulling in an additional dependency. That not only adds to the library upkeep burden but can be off-putting to users.

Though likely fine with most users this change can be anywhere from annoying to those that prefer a different error library to particularly burdensome on those in companies where each dependency must be approved by security.

**Comment by danieleades** [comment]
> annoying to those that prefer a different error library 

`thiserror` is not exposed in the API, it's just a compile-time only helper which is precisely equivalent to the existing error implementation this library already has- it just replaces the boilerplate with a derive macro.

> particularly burdensome on those in companies where each dependency must be approved by security.

This i understand, as this is something i have to manage in my day job. `thiserror` is small, well-maintained, extremely widely-used, maintained by a well-known author, etc. Not a high-risk dependency by any means. It's also so widely-used that any company that both uses Rust code *and* has to vet transitive dependencies of libraries they use is very likely to have already reviewed this library.

**Comment by danieleades** [comment]
@davegarred any movement on this? Does my previous comment answer your questions?

**Comment by davegarred** [comment]
Hi @danieleades, I think we could give it a try. I do need you to resolve the conflicts though.

**Pull request merged**
